preprocessing:
  target: price
  features: [area, bedrooms, bathrooms, stories, parking]


model:
  type: random_forest  # switch name here to select which model to test

  # parameters for each model
  linear_regression:
    fit_intercept: true
    normalize: false

  random_forest:
    n_estimators: 100
    max_depth: 5

  gradient_boosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3


train:
  test_size: 0.2  # 80/20 test train split
  random_state: 42
  alpha: 0.1
  epochs: 50
  batch_size: 32